version: "3.8"
services:
  redis:
    image: redis:latest
    command: redis-server --port 6379
    ports:
      - "6379:6379"
  mariadb:
    image: mariadb:latest
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
    environment:
      MARIADB_ROOT_PASSWORD: 6599
      MYSQL_DATABASE: kooapi
    ports:
      - "3306:3306"
  appserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - local.env
    depends_on:
      - redis
      - mariadb