version: "3.8"
services:
  redis:
    image: redis:latest
    command: redis-server --port 6379
    ports:
      - "6379:6379"
  mysqldb:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=test
    ports:
      - "3306:3306"
  appserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8282:8080"
    env_file:
      - local.env
    depends_on:
      - redis
      - mysqldb
    environment:
      - TZ=Asia/Seoul
