version: "3.8"
services:
  redis:
    image: redis:latest
    command: redis-server --port 6379
    ports:
      - "6379:6379"
  appserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - local.env
    depends_on:
      - redis